"""empty message

Revision ID: 93eccf36f75b
Revises: 17cce1181f79
Create Date: 2020-05-05 16:56:32.224537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eccf36f75b'
down_revision = '17cce1181f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable= False)
     # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
